# Generated by Django 3.2 on 2022-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Completed',
            field=models.DateTimeField(null=True),
        ),
    ]
