# Generated by Django 3.2 on 2022-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Created',
            field=models.DateTimeField(blank=True),
        ),
    ]
