# Generated by Django 3.2 on 2022-06-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20220626_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DecimalField(decimal_places=0, max_digits=2)),
                ('disbursement', models.DecimalField(decimal_places=2, max_digits=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.merchant')),
            ],
        ),
    ]
